### ISSUE TITLE
The agent not working as expected in a Rails 7.1.3 application

### ISSUE THREAD

**Issue by olivierbuffon** [inigolabs/inigo-rb#18]
Hi there! 

I think there is something wrong with this plugin, at least in my case.
I have a ruby application in 7.1.3 using the last version of `graphql-ruby` gem.
I followed all the instruction I found [here](https://docs.inigo.io/product/agent_installation/ruby_on_rails) but I can't make it work as expected.
I keep having the same error `uninitialized constant Inigo::Tracer` when adding the `use Inigo::TracerInigo` inside my schema class.
Same problem with the puma plugin ` Unable to find plugin: inigo (Puma::UnknownPlugin)`

Am I missing something?

Thanks.

**Comment by kreyyser** [comment]
Hi  @olivierbuffon 

The graphql-ruby dependency requirement was outdated and the issue was reproducible on our end.
The latest gem version (v0.29.6) should fix your issue.
We are updating our library to remove the deprecated use of Tracing::PlatformTracing and this will be available in the next version.
